### ISSUE TITLE
Feature: Reset Password with a verification email

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#100]
* [x] Reset password modal for unauthenticated user
    * Add a modal with a `TextField` with `type="email"` and a submit button which will send an email containing the reset password link. Firebase SDK supports this feature and we can customize the email content on Firebase console. After submitting, close the modal and show a succes snackbar, ~~show a snackbar error if and only if a network issue occurs~~.
* [x] Reset password modal for unauthenticated user
   * Same as the modal for unauthenticated user and...
    * Fill the `TextField` with the current user's email
* [x] Change the "Need a new password?" text below to "Forget password?"

![Screenshot_20211109-193001_Chrome.jpg](https://user-images.githubusercontent.com/52666982/141027569-1af122f4-938d-49cf-bbc6-0fb3717cceb7.jpg)

**Comment by vitokhangnguyen** [comment]
This makes sense, will include in #65... Although as you mention... we don't have reset password feature yet
