### ISSUE TITLE
Shifted layout inside /account/profile

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#105]
Seem like toggling one action field also trigger re-render on other action fields. 

https://user-images.githubusercontent.com/52666982/141650472-8b57da61-f5d4-4898-9e49-64d9595134df.mp4

**Comment by vitokhangnguyen** [comment]
Any idea why this might happen?

**Comment by vitokhangnguyen** [comment]
So after 5 mins of investigation, this only happens when the profile for the user does not exist which makes SWR returns `undefined` for every redner. And I think `useMemo` treats `unedefined` as a changed value for every render so any componenet that uses `userUserProfile()` gets re-rendered

**Comment by vitokhangnguyen** [comment]
Eureka!! Disabling `revalidateOnMount` for `userProfile` fixes the issue.

**Comment by vitokhangnguyen** [comment]
Don't worry about what I said before, doesn't really work... fixing #106 will fix the layout shift but the underlining issue of SWR is still there...

**Comment by Andrewnt219** [comment]
Just put a placeholder then, to prevent the shifting.

**Comment by Andrewnt219** [comment]
I remember seeing some components defining "profile" as a dependency instead of profile.dob, not sure if that helps.

**Comment by vitokhangnguyen** [comment]
> I remember ~~seeing~~ reviewing some components defining "profile" as a dependency instead of profile.dob, not sure if that helps. 

Will try that tonight but I doubt it...

**Comment by vitokhangnguyen** [comment]
One possible fix but I don't recommend is changing the API to return 200 with data null of profile doesn't exist...

Or we can use axios interceptor to transform a 404 response to a 200 with data null...

**Comment by Andrewnt219** [comment]
Removing `isProfileReady` seems to solve the issue.

**Comment by vitokhangnguyen** [comment]
> Removing `isProfileReady` seems to solve the issue. 

Yea but that would give a flash of content as if the user does not have a profile even if they do, we prefer to use it to control a loading state instead

**Comment by Andrewnt219** [comment]
Don't see much of a UX improvement here. Flash of unauthenticated content is the quirk of client-side authenticating. If we really want to avoid confusing users, maybe don't render the page until we fetch the profile?

https://www.awesomescreenshot.com/video/6005422?key=2b36532f27f29863a5be413ef3719600

**Comment by vitokhangnguyen** [comment]
> Removing `isProfileReady` seems to solve the issue.
> 
> Missing gender success response btw.
> 
> https://www.awesomescreenshot.com/video/6005380?key=cbec8682d5ddeeb1b950cf0e5a00c623

Can't produce the missing gender change response

**Comment by Andrewnt219** [comment]
nvm then, that's video is for comparing UX with and without `isProfileReady `

**Comment by vitokhangnguyen** [comment]
I think I found a fix to the underlining issue, maiing the PR
