### ISSUE TITLE
Action fields should have placeholders

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#106]
The placeholders will prevent layout shifts on fetching the profile. I cannot reproduce in this video, but thr first time I logged in on my phone, it took a few seconds to show the data. 

https://user-images.githubusercontent.com/52666982/141650715-5a963ff2-0a2f-4480-b3b9-9d144a1f0f79.mp4

**Comment by vitokhangnguyen** [comment]
Same issue as #105, no?

**Comment by Andrewnt219** [comment]
Not really, #105 is a React problem. This is just a UX for loading state.

**Comment by vitokhangnguyen** [comment]
Let's fix this by just not showing the action fields until `isProfileReady` is `true`
