### ISSUE TITLE
Feature: Create protected routes / page guarding mechanism

### ISSUE THREAD

**Issue by vitokhangnguyen** [Andrewnt219/rent-near-me#71]
Examples of protected routes:

* /account
* /account/profile
* /account/security
* ...

**Comment by Andrewnt219** [comment]
I thought we kinda have this already? In /account/security.

Great suggestion by Grammarly btw

![image](https://user-images.githubusercontent.com/52666982/139512228-1a522b63-ce09-4c85-847e-f235a0f5da7a.png)

**Comment by vitokhangnguyen** [comment]
> I thought we kinda have this already? In /account/security.

Can you quote the code directly? I don't see anything related to this...

And maybe Grammarly is asking to be paid 😂

**Comment by Andrewnt219** [comment]
I remember having this feature 

https://user-images.githubusercontent.com/52666982/139515756-bf05bb71-5642-4195-83bb-fd821e0e88c9.mp4

**Comment by Andrewnt219** [comment]
So how are you going to implement private routes? I did that in React Router but not sure about Next.js.

**Comment by vitokhangnguyen** [comment]
Yea, i'll do it. The issue is already assigned to me.

Private routing in Next.js would be compeltely different since we don't have  a routing component... they're all file-system-based

**Comment by Andrewnt219** [comment]
nvm, just want to finish discussing the solution here, but I guess we can do that in the PR.

**Comment by vitokhangnguyen** [comment]
@Andrewnt219 

My plan is to create a HOC like `requireAuth()` that can wrap around any page that must be logged in to see. It can optionally take a 2nd parameter `emailVerified`, default to `true` which will also require the user to have already verified their email.

**Comment by Andrewnt219** [comment]
Next 12 has support for [middlewares](https://vercel.com/features/edge-functions). This may help. 

https://github.com/vercel/examples/tree/main/edge-functions/basic-auth-password/pages

**Comment by vitokhangnguyen** [comment]
> Next 12 has support for [middlewares](https://vercel.com/features/edge-functions). This may help.
> 
> https://github.com/vercel/examples/tree/main/edge-functions/basic-auth-password/pages

Nice, this would definitely help.

However, this code runs on the server and we will have to check the user's token with Firebase. Instead, if we do this on client-side, we just need to check if ``user` in `const { user } = useAuth()` exists which has some performance advantage since we save a trip to the server.

I'm just noting it here for my consideration. Let me look more into it and see.

**Comment by Andrewnt219** [comment]
Make sense.

Have you checked [the docs](https://nextjs.org/docs/authentication#authenticating-statically-generated-pages) or [this example](https://github.com/vercel/next.js/tree/canary/examples/with-firebase-authentication)?

**Comment by vitokhangnguyen** [comment]
> Make sense.
> 
> Have you checked [the docs](https://nextjs.org/docs/authentication#authenticating-statically-generated-pages) or [this example](https://github.com/vercel/next.js/tree/canary/examples/with-firebase-authentication)?

Just checked out `next-firebase-auth`, from their repo:

```
# When (Not) to Use this Package

...

If your app only uses static pages or doesn't need the Firebase user for SSR, use the Firebase JS SDK directly to load the user on the client side.
```

This seems to be the direction of our app (no SSR, just uses SWR to fetch data).
