### ISSUE TITLE
Update tailwindcss tokens for Minimals

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#80]
https://minimals.cc/components

- [x] [Color](https://minimals.cc/components/color) #79
- [x] [Typography](https://minimals.cc/components/typography) #79
- [x] [Shadows](https://minimals.cc/components/shadows) #79
- [x] [Grid/Spacing](https://minimals.cc/components/grid) #79
- [x] [Icons](https://minimals.cc/components/icons) (Migrate icons to [@iconify/react](https://docs.iconify.design/icon-components/react/))  
- [x] Fix broken tokens

**Comment by vitokhangnguyen** [comment]
@Andrewnt219 Consider [@iconify/react](https://docs.iconify.design/icon-components/react/). This is the icon set used by Minimals I beleive

**Comment by Andrewnt219** [comment]
So we switch from react-icons to @iconify/react?

**Comment by vitokhangnguyen** [comment]
> So we switch from react-icons to @iconify/react?

Yea, let's do this. Look like `iconify` provides a lot more icons and also utilities functions/types as well.  I'll do the migration for this.

**Comment by Andrewnt219** [comment]
I'm working on the switch.
