### ISSUE TITLE
DOB picker error shows timestamp instead of date

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#83]
![image](https://user-images.githubusercontent.com/52666982/139738818-0210e1f1-05c0-4ca9-95c0-f5a413434fe8.png)

## Reproduce

Pick a DOB later than today

## Expect

Error shows more readable date

**Comment by vitokhangnguyen** [comment]
Ideally, the datepicker should restrict the user from selecting the date that are out of range as well
