### ISSUE TITLE
Refactor: Use `react-form-hook`'s `<FormProvider>` instead of passing `control` to individual fields

### ISSUE THREAD

**Issue by vitokhangnguyen** [Andrewnt219/rent-near-me#90]
# Background

Currently, we have this long-winded code for every form to pass the `name` and, more importantly, the `control` of the form to the `useController` hook of each field in the form.

```js
  const controllers: Controllers<RegisterFormModel> = {
    firstName: {
      control,
      name: 'firstName',
    },
    lastName: {
      control,
      name: 'lastName',
    },
    gender: {
      control,
      name: 'gender',
    },
    dob: {
      control,
      name: 'dob',
    },
    email: {
      control,
      name: 'email',
    },
    password: {
      control,
      name: 'password',
    },
  };
```

# Proposal

We can avoid passing the `control` of the form to individual fields by wrapping the form around a `<FormProvider>`  exported from `react-form-hook` (See the description of the `control` property in the [docs](https://react-hook-form.com/api/usecontroller)).

By doing this, we can eleminate the `controllers` altogether and pass only the `name` directly to the fields.

Official example for the use of `<FormProvider>` can be found [here](https://codesandbox.io/s/react-hook-form-form-context-2703c?file=/src/index.js:327-339).

**Comment by Andrewnt219** [comment]
Let's do this 👏.
