### ISSUE TITLE
Cannot reopen login modal after closing

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#92]
## Reproduce
Branch: dev

- From homepage, open Menu > Login & Security
- Close sign in modal
- open Menu > Login & Security

## What happened
Cannot open the login modal

## Expect
Login modal should open

**Comment by vitokhangnguyen** [comment]
This is not a bug I think. After you close the login modal, you're still on `/acount/security`, navigating to the same URL with `bext/router` would not trigger a navigation, therefore, the login modal won't popup again.

If after you close the login modal, you go to menu -> login, the modal will popup again.
