### ISSUE TITLE
Login modal is closed on wrong credentials

### ISSUE THREAD

**Issue by Andrewnt219** [Andrewnt219/rent-near-me#93]
## Reproduce
Branch: dev

- From homepage, open Menu > Login
- Enter the wrong username and password
- Press login

## What happened
The modal is closed

## Expect
Login should open and show an error message

---

I suspect this is because react-hook-form doesn't properly handle errors thrown in `handleSubmit`. I might have done it wrong, but their docs is not accurate. This does not handle the throw (even though their docs says so)
```
const onSubmit = () => {
  throw new Error('Something is wrong')
}

handleSubmit(onSubmit).catch((e) => {
  // you will need to catch that error
})
```

In the other project, [I handle this with mutation from react-query](https://github.com/Andrewnt219/seneca-course-reviews/blob/main/src/modules/auth/components/SignupForm/SignupForm.tsx). SWR seems to has the same concept for [mutation](https://swr.vercel.app/docs/mutation), but I'm not sure.

**Comment by vitokhangnguyen** [comment]
Yea,. this is a bug.

I think it's just because how I write the submit handler:

```js
  const onSubmit = form.handleSubmit(async (data) => {
    await AuthService.signInWithEmail(
      data.email,
      data.password,
      data.keepLogIn
    ).catch((err) => setSubmitError(err.error_description || err.message));

    loginModal.hide();
  });
```

I should do `loginModal.hide();` in a `then` clause because a promise with a `catch` clause won't throw an error.
